#import modules
import pw_gen

#Password Generator(This should be an option, if user wants to ask system to generate a password
# or enter and check if the password is strong enough)
print(f"Computer Generated this for you: {pw_gen.pw}")

#Ask user if they want to use the pw generated by the computer
pw_ok = input("Do you want to keep this password(y/n) : ").lower()

if pw_ok ==  "y" or pw_ok == "yes":
    print("Cools!!! Exiting Program....")
    exit()
else:
    up = input("Enter your password: ")


#Program to check the strength of the Password, Give examples of strong password and generate the superstrong passwords

#Password Strength Checker
def password_checker(password):
    issues = []
    #check for password length
    if len(password) < 10:
        issues.append("Password length below 10 characters")

    #check for digit in the password
    if not any(char.isdigit() for char in password):
        issues.append("Add numbers to your password")

    #Check for upper case
    if not any(char.isupper() for char in password):
        issues.append("Add at-least one upper case character")

    #Check for lower case
    if not any(char.islower() for char in password):
        issues.append("Include lower case characters too")

    #Check special character
    if not any(char in "!@#$%^&*()-_=+" for char in password):
        issues.append("Include a special character such as !@#$%^&*()-_=+")

    #loop through the list "issues" and display the list
    for issue in issues:
        print(issue)

    # display password strength if all the conditions are met
    if len(issues) == 0:
        return "Your Password is: Strong"

#take password from the user
# user_pass = up

#logic to call the function & print the result
strength = password_checker(up)
print(strength)


#Example Passwords(Only show if password strength is not strong)
# strong_passwords = []




